# Generated by Django 3.0.7 on 2020-08-26 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collection',
            old_name='issues',
            new_name='comics',
        ),
        migrations.RenameField(
            model_name='collection',
            old_name='tie_in_issues',
            new_name='tie_in_comics',
        ),
        migrations.RenameField(
            model_name='reading_order',
            old_name='issue',
            new_name='comic',
        ),
    ]
